# Generated by Django 5.1.1 on 2024-10-18 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
